/**
 * Phase 7c — give every revista PDF a first-party URL on misionessim.org
 * instead of exposing the raw Contentful CDN URL.
 *
 *   /revistavamos/lucha-espiritual/LuchaEspiritualVamosMarzo26-4.pdf
 *     -> https://assets.ctfassets.net/<space>/<id>/<hash>/LuchaEspiritual...pdf
 *
 * Implemented as Vercel **rewrites** (proxy, URL unchanged in the browser),
 * not redirects. Note that `output: "export"` forbids Next's own rewrites()
 * because they need a server — but vercel.json rewrites are applied at the
 * edge, before the static assets are consulted, so they work fine here.
 *
 * Why not a single wildcard rule: the Contentful asset URL embeds an opaque
 * entry id and content hash that cannot be derived from the slug or filename,
 * so each edition needs its own explicit mapping. 119 rules, generated.
 *
 * Ordering note: `/la-revista/:path*` -> `/revistavamos/:path*` already exists
 * in the redirects block, and Vercel evaluates redirects before rewrites, so
 * the legacy `/la-revista/...` PDF path 301s into the canonical one for free.
 *
 * This script rewrites ONLY the `/revistavamos/**.pdf` rewrites in
 * vercel.json, so hand-written rules and the `/recursos/**` block generated by
 * build-legacy-redirects.ts are preserved.
 *
 * Re-runnable: `yarn build:revista-rewrites`. Re-run whenever an edition is
 * added or its PDF is re-uploaded (the Contentful hash changes on re-upload).
 */
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { buildRevistaCatalogue } from "../lib/content/revista-catalogue";
import { revistaPdfPath } from "../lib/publishing/paths";

const VERCEL_JSON = path.join(process.cwd(), "vercel.json");

export interface Rewrite {
  source: string;
  destination: string;
}

/** Rewrites are owned by prefix; see the note in main(). */
export const REVISTA_PDF_PREFIX = "/revistavamos/";

async function fetchRevistaPdfs(): Promise<
  Array<{ id: string; slug: string; url: string; fecha: string }>
> {
  // Read at call time, not module scope: importers may populate the
  // environment (e.g. from .env.local) after this module has been hoisted.
  const SPACE_ID = process.env.CONTENTFUL_SPACE_ID;
  const CDA_TOKEN = process.env.CONTENTFUL_ACCESS_TOKEN;
  if (!SPACE_ID || !CDA_TOKEN) {
    throw new Error("CONTENTFUL_SPACE_ID / CONTENTFUL_ACCESS_TOKEN not set");
  }
  const query = `{
    revistaCollection(order: fecha_DESC, limit: 200) {
      items { sys { id } slug fecha revistaPdf { url } }
    }
  }`;
  const res = await fetch(
    `https://graphql.contentful.com/content/v1/spaces/${SPACE_ID}/environments/master`,
    {
      method: "POST",
      headers: {
        Authorization: `Bearer ${CDA_TOKEN}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ query }),
    },
  );
  const json = (await res.json()) as {
    errors?: unknown;
    data: {
      revistaCollection: {
        items: Array<{
          sys: { id: string };
          slug: string;
          fecha: string;
          revistaPdf?: { url: string } | null;
        }>;
      };
    };
  };
  if (json.errors) throw new Error(JSON.stringify(json.errors));

  return json.data.revistaCollection.items
    .filter((r) => r.revistaPdf?.url && r.slug)
    .map((r) => {
      const url = r.revistaPdf!.url.startsWith("//")
        ? `https:${r.revistaPdf!.url}`
        : r.revistaPdf!.url;
      return { id: r.sys.id, slug: r.slug, url, fecha: r.fecha };
    });
}

/**
 * The single source of truth for what the `/revistavamos/**.pdf` rewrites
 * should be. Both the generator below and `check-revista-rewrites.ts` call
 * this, so the check can never disagree with what a regeneration would write.
 */
export async function computeRevistaRewrites(): Promise<Rewrite[]> {
  const revistas = await fetchRevistaPdfs();

  const rewrites = buildRevistaCatalogue(revistas).map(({ entry, slug }) => {
    const source = revistaPdfPath(slug, entry.url);
    if (!source) throw new Error(`Could not derive PDF path for ${entry.id}`);
    return { source, destination: entry.url };
  });

  rewrites.sort((a, b) => a.source.localeCompare(b.source));
  return rewrites;
}

async function main() {
  console.log("Fetching revista PDFs from Contentful ...");
  const rewrites = await computeRevistaRewrites();
  console.log(`  -> ${rewrites.length} editions with a PDF`);

  const raw = await readFile(VERCEL_JSON, "utf8");
  const config = JSON.parse(raw) as {
    rewrites?: Rewrite[];
    [k: string]: unknown;
  };

  // Own only the `/revistavamos/**.pdf` rules — `/recursos/**` rewrites are
  // generated by build-legacy-redirects.ts and must survive a re-run here.
  const kept = (config.rewrites ?? []).filter(
    (r) => !r.source.startsWith(REVISTA_PDF_PREFIX),
  );
  config.rewrites = [...kept, ...rewrites];

  await writeFile(VERCEL_JSON, JSON.stringify(config, null, 2) + "\n");

  const redirects = (config.redirects as unknown[] | undefined)?.length ?? 0;
  console.log(
    `\nWrote ${rewrites.length} revista rewrites to vercel.json (kept ${kept.length} others)`,
  );
  // Vercel caps the redirects array at 2,048 entries (source/destination
  // strings at 4,096 chars). The ~800 pending /wp-content/uploads redirects
  // therefore fit in the plain array — no need for the proprietary
  // `bulkRedirectsPath`, which would deepen platform lock-in for no gain.
  console.log(
    `Budget: ${redirects} redirects (limit 2,048) + ${rewrites.length} rewrites.`,
  );
  console.log("\nSample:");
  for (const r of rewrites.slice(0, 3)) {
    console.log(`  ${r.source}\n    -> ${r.destination}`);
  }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
